services:
  - type: web
    name: obratrack-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:backend
    startCommand: npm run start -w backend
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true